global:
  scrape_interval:     5s 
  evaluation_interval: 5s
scrape_configs: 
  - job_name: prometheus
    scrape_interval: 10s
    kubernetes_sd_configs:
      - role: pod
  - job_name: 'myapp'
    scheme: http
    static_configs:
    - targets: ['sample.default:9090']
